#!/bin/sh

# Make sure configuring packages do not start any services
if [ ! -e /usr/sbin/policy-rc.d ] ; then
    cat > /usr/sbin/policy-rc.d <<EOF
#!/bin/sh
exit 101
EOF
    chmod a+rx /usr/sbin/policy-rc.d
    policyd=true
else
    policyd=false
fi
for f in /usr/lib/freedombox/setup.d/* ; do
    echo "running $f"
    $f
done

# default configuration
UNKNOWN_SETUP=1 # 05_network: always configure default networking.

export UNKNOWN_SETUP

# Allow services to start after upgrading
if $policyd ; then
    rm /usr/sbin/policy-rc.d
fi
