#!/bin/sh
#
# Exports the currently-detected hardware to MACHINE.
#
# Return true if the MACHINE was detected, and false otherwise.
#
# Currently look in /sys/devices for indicators.
#
# Other possibilities:
#
# echo $(cat /proc/device-tree/model)
# Globalscale Technologies Dreamplug

MACHINE=""

case $(dpkg --print-architecture) in
    armel)
	    # Matches these:
	    # /sys/devices/gpio-leds.1/leds/dreamplug:blue:bluetooth
	    # /sys/devices/gpio-leds.1/leds/dreamplug:green:wifi_ap
	    # /sys/devices/gpio-leds.1/leds/dreamplug:green:wifi
	    if find /sys/devices -name 'dreamplug:*' | grep -q dreamplug: ; then
            MACHINE=dreamplug
	    fi

	    # Matches these:
	    # /sys/devices/leds.7/leds/beaglebone:green:heartbeat
	    # /sys/devices/leds.7/leds/beaglebone:green:mmc0
	    # /sys/devices/leds.7/leds/beaglebone:green:usr2
	    # /sys/devices/leds.7/leds/beaglebone:green:usr3
	    if find /sys/devices -name 'beaglebone:*' | grep -q beaglebone: ; then
            MACHINE=beaglebone
	    fi
	    ;;

    armhf)
	    # Matches these:
	    # /sys/devices/leds.7/leds/beaglebone:green:heartbeat
	    # /sys/devices/leds.7/leds/beaglebone:green:mmc0
	    # /sys/devices/leds.7/leds/beaglebone:green:usr2
	    # /sys/devices/leds.7/leds/beaglebone:green:usr3
	    if find /sys/devices -name 'beaglebone:*' | grep -q beaglebone: ; then
            MACHINE=beaglebone
	    fi
	    ;;
esac

export MACHINE

if [ -n "$MACHINE" ]
then
    return 0
fi

return 1
