#!/bin/sh
#
# Get ORPort number from Tor control port.
# Usage: tor-get-orport
#
# Tor control port must be enabled on localhost port 9051.
#

cookie=`perl -e 'my $a=do{local(@ARGV,$/)="/var/run/tor/control.authcookie"; <>}; warn unpack("H*",$a)' 2>&1 | awk '{print $1}'`

response=`nc localhost 9051` <<EOF
AUTHENTICATE $cookie
GETINFO net/listeners/or
QUIT
EOF

echo $response | awk -F'[:\"]' '/net\/listeners\/or/ { print $3 }'
