#!/bin/sh

# Avoid etckeeper problem (refuses to commit) because git picked a
# email address with an empty domain.
if which etckeeper > /dev/null 2>&1 && \
    [ ! -e /etc/mailname ] &&
    [ -z "$(git config --global --get user.email)" ] ; then
    git config --global user.email "root@localhost"
    etckeeper commit -m "Status before freedombox-setup run."
fi
