#!/bin/sh

set -e

# Put documentation in the fbx users home directory, if it exist
if [ -d /home/fbx ] ; then
    zcat /usr/share/doc/freedombox-setup/README.fbx-home.gz > /home/fbx/README
    chmod a+rx /home/fbx/README
    chown fbx /home/fbx/README
else
    echo info: Not adding /home/fbx/README.
fi
