#! /bin/bash
#
# Copyright 2012 by Nick Daly <nick.m.daly@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# projects
#
# Installs external projects to the system.
#
# FIXME Each of these packages should eventually be packaged in Debian
# and we should pull them in as dependencies during the install
# process.  This is a hack till then.

# We don't tolerate errors.
set -e

fbxuid=1000

fbxgit="$(getent passwd 1000|cut -d: -f4)"
if [ -z "$fbxgid" ] ; then
    fbxgid=1000
fi

homedir="$(getent passwd $fbxuid|cut -d: -f6)"
if [ -z "$homedir" ] ; then
    homedir=/home/fbx
fi

if [ -n "$1" ]
then
    homedir=$1
fi
if [ -n "$2" ]
then
    user=$2
fi

if [ ! -e "$homedir" ]
then
    mkdir -p "$homedir"
fi

echo "Adding a few FreedomBox projects to $homedir."

git clone git://github.com/NickDaly/freedom-maker.git $homedir/freedom-maker
git clone git://github.com/NickDaly/Plinth.git $homedir/plinth
git clone git://github.com/jvasile/freedombox-privoxy $homedir/freedombox-privoxy
git clone git://github.com/NickDaly/freedombox-todos.git $homedir/freedombox-todos
git clone git://github.com/NickDaly/key-report.git $homedir/key-report
git clone git://github.com/NickDaly/withsqlite.git $homedir/withsqlite
# hg clone https://hg@bitbucket.org/nickdaly/plugserver $homedir/plugserver
git clone git://github.com/NickDaly/FreedomBuddy.git $homedir/freedombuddy
git clone git://gitorious.org/project-publish/project-publish.git $homedir/freedombuddy/publish
ln -s $homedir/freedombuddy/issues $homedir/freedombuddy/publish/.
ln -s $homedir/freedombuddy/wiki $homedir/freedombuddy/publish/.
rst2html $homedir/README $homedir/README.html

chown -R $fbxuid:$fbxgid $homedir
