#!/bin/sh
#
# Set up jwchat to work out of the box.

set -e

# Set hostname for ejabberd
echo "ejabberd ejabberd/hostname string `hostname`" | debconf-set-selections

# An alternative XMPP server is prosody
apt-get install -y jwchat ejabberd

# Enable BOSH module for ejabberd
sed -i '/mod_last/i \
  {mod_http_bind, []},' /etc/ejabberd/ejabberd.cfg

# Disabling the default site make jwchat the default site.
a2dissite 000-default
