#!/bin/sh
#
# Set up jwchat to work out of the box.

set -e

# An alternative XMPP server is prosody
apt-get install -y jwchat ejabberd

# Disabling the default site make jwchat the default site.
a2dissite 000-default
