#!/bin/sh
#
# Make sure generated images complies with licenses requiring the
# source to be available, by providing the source of every package
# used.

# TODO Remove on 1/1/15: " || [ 'true' = '$NOSOURCE' ]"
if [ 'false' = "$SOURCE" ] || [ 'true' = '$NOSOURCE' ] ; then

    echo "Not adding source packages to filesystem (SOURCE=false)"
    exit 0
else
    echo "Adding source packages to file system"
fi

targetdir=/usr/src/packages

echo "Adding source packages to filesystem in $targetdir"
apt-get update || true
dpkg --get-selections > /tmp/selections
mkdir -p $targetdir
cd $targetdir

cut -f 1 < /tmp/selections | \
    cut -d ':' -f 1 > /tmp/packages
apt-get source -m --download-only `cat /tmp/packages`

rm /tmp/selections /tmp/packages
