#!/bin/sh

. /lib/lsb/init-functions

log_action_begin_msg "Creating SSH keys"
rm /etc/ssh/ssh_host_*
if dpkg-reconfigure openssh-server ; then
    log_action_end_msg 0
else
    log_action_end_msg 1
fi
