#!/bin/sh
#
# see http://lists.gnupg.org/pipermail/gnupg-users/2003-March/017376.html

# . /lib/lsb/init-functions

#log_action_begin_msg "Creating GPG key"
#echo "  Need to create other keys."
#if gpg --batch --gen-key ; then
#    log_action_end_msg 0
# else
#    log_action_end_msg 1
# fi
