#!/bin/sh
# configure wireless access point with spinifex's prebuilt firmware

# Disabled
exit 0

echo "Configuring WIFI..."

echo "  Sleeping 30s for DHCP"
sleep 30    # wait for dhcp

# TODO use the firmware-libertas package on the DreamPlug if users want non-free
# software installed on the device.

echo "  Installing UAP Firmware."
wget -O /tmp/marvell_wifi_firmware.tar.gz \
    http://www.spinifex.com.au/plugs/downloads/dreamplug/marvell_wifi_firmware.tar.gz
tar -C /tmp -zxf /tmp/marvell_wifi_firmware.tar.gz
mkdir -p /lib/firmware/mrvl
cp /tmp/lib/firmware/mrvl/* /lib/firmware/mrvl

echo "Done Configuring WIFI."

