#!/bin/sh
#
# selectively configure wireless access point with libertas firmware.

echo "Configuring WIFI..."

# If users have selected non-free packages, install firmware-libertas.
. machine-detect
if [ "$MACHINE" = "dreamplug" ]
then
    if [ -n "`grep nonfree /etc/apt/sources.list`" ]
    then
        echo "Installing non-free WIFI package: firmware-libertas..."
        apt-get install firmware-libertas
    else
        echo "Non-free packages disabled.  Skipping DreamPlug WIFI config."
    fi
else
    echo "Not a DreamPlug.  Skipping DreamPlug WIFI config."
fi

echo "Done Configuring WIFI."
