#!/bin/bash
#
# Update the kernel if package flash-kernel is install unless
# requested otherwise.

. /lib/lsb/init-functions

if ! type flash-kernel > /dev/null 2>&1 ; then
    log_warning_msg "Skipped Flashing Kernel: flash-kernel is not installed."
    exit 0
fi

if [ -e /var/freedombox/dont-tweak-kernel ]
then
    log_warning_msg "Skipped Flashing Kernel."
    exit 0
else
    . /usr/lib/freedombox/machine-detect
    if [ "$MACHINE" = "dreamplug" ]; then
        kernel_version="$(/bin/ls /boot/vmlinuz-*-kirkwood | sort -rn | head -n1 | sed s#/boot/vmlinuz-##)"
    else
        if [ "$MACHINE" = "beaglebone" ]; then
            kernel_version="$(/bin/ls /boot/vmlinuz-*-armmp | sort -rn | head -n1 | sed s#/boot/vmlinuz-##)"
        fi
    fi

    log_action_begin_msg "Flashing Kernel version $kernel_version "

    if flash-kernel "$kernel_version" ; then
	log_action_end_msg 0
    else
	log_action_end_msg 1
    fi
fi
